apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app-server
        image: iad.ocir.io/oracle-cloudnative/prometheus-app-monitor:metrics
        imagePullPolicy: Always
        command: ["./main"]
        ports:
        - name: demo-app-server
          containerPort: 8080
          protocol: TCP
---
# Service Definition
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30001
  selector:
    app: demo-app
